# (c) 2017 KAI OS TECHNOLOGIES (HONG KONG) LIMITED All rights reserved. This
# file or any portion thereof may not be reproduced or used in any manner
# whatsoever without the express written permission of KAI OS TECHNOLOGIES
# (HONG KONG) LIMITED. KaiOS is the trademark of KAI OS TECHNOLOGIES (HONG KONG)
# LIMITED or its affiliate company and may be registered in some jurisdictions.
# All other trademarks are the property of their respective owners.

variables:
  GIT_DEPTH: 1
  DEFAULT_DOCKER_IMAGE: "${CI_REGISTRY}/re/kaios-build/next/desktop:latest"
  # GIT_CLONE_PATH would be overidden with "koost" if pipeline gets triggered from within koost
  GIT_CLONE_PATH: ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/gecko

.global_setup: &global_setup
  - echo -e "machine ${CI_SERVER_HOST}\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
  - git config --global url."${CI_SERVER_URL}/".insteadOf "git@${CI_SERVER_HOST}:"

.koost_setup: &koost_setup
  - |
    if [[ ${GIT_CLONE_PATH##*/} == koost ]]; then
      printf "\033[0;31mYou're using GECKO_PATH defined from ${CI_PROJECT_PATH} !\033[0m\n"
      cd ${GECKO_PATH}
      git init
      git fetch ${CI_SERVER_URL}/KaiOS/gecko-dev.git next --no-tags --depth 1
      git checkout FETCH_HEAD
      check_format_opt="${check_format_opt} --koost"
    else
      cd ${GIT_CLONE_PATH}
      git clone ${CI_SERVER_URL}/KaiOS/koost.git -b next --depth 1
    fi
  - |
    rm -rf gonk-q
    if [ "${CI_JOB_NAME}" == "build:arm" ]; then
      git clone ${CI_SERVER_URL}/KaiOS/dummy/gonk-q.git --depth 1
    fi

default:
  image: $DEFAULT_DOCKER_IMAGE
  tags:
    - gecko-dev
  before_script:
    - *global_setup
    - *koost_setup

stages:
  - lint
  - build

lint:all:
  stage: lint
  tags:
    - gecko-lint
  variables:
    DEFAULT_DOCKER_IMAGE: "${CI_REGISTRY}/re/kaios-build/next/daily:latest"
    # force the runner not to initialize the repository
    GIT_STRATEGY: none
  before_script:
    - *global_setup
  script:
    - apt-get install jq -yy
    - |
      cd ${CI_BUILDS_DIR}
      depth=$(curl -s \
        -H "Private-Token: ${GITLAB_API_KEY}" \
        "${CI_API_V4_URL}/projects/${CI_MERGE_REQUEST_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/commits" \
        | jq length)
    - |
      rm -rf ${GIT_CLONE_PATH}
      git clone ${CI_MERGE_REQUEST_SOURCE_PROJECT_URL}.git \
        -b ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} \
        --depth $((depth+1)) \
      ${GIT_CLONE_PATH}
    - 'check_format_opt="--against HEAD~${depth} -v"'
    - *koost_setup
    - ./check-format.sh ${check_format_opt}
  only:
    - merge_requests
  except:
    refs:
      - pipelines
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /skip-lint|^WIP\:/

build:desktop:
  variables:
    MOZ_OBJDIR: 'objdir-desktop-gecko'
    MOZCONFIG: 'mozconfig-b2g-desktop'
  stage: build
  before_script:
    - '[ "$(cat ${HOME}/.mozbuild/ver)" = "3" ] || curl https://packages.preprod.kaiostech.com/ndk/v3/mozbuild.tar.bz2 | tar -C ${HOME}/ -xj'
    - *global_setup
    - *koost_setup
  script:
    - ./mach build
    - ./mach package
  artifacts:
    expire_in: 1 week
    paths:
      - "objdir-desktop-gecko/dist/b2g-*"
  only:
    - merge_requests
  except:
    - pipelines

build:emulator:
  before_script:
    - *global_setup
    - git clone --depth 1 git@git.kaiostech.com:KaiOS/dummy/emulator-10.git > /dev/null 2>&1
  variables:
    DEFAULT_DOCKER_IMAGE: "${CI_REGISTRY}/re/kaios-build/next/daily:latest"
    GONK_PATH: "${CI_PROJECT_DIR}/emulator-10"
    GECKO_OBJDIR: "${CI_PROJECT_DIR}/objdir-emulator-gecko"
    GONK_PRODUCT_NAME: generic_x86_64
    PLATFORM_VERSION: 29
    TARGET_ARCH: x86_64
    TARGET_ARCH_VARIANT: x86_64
    TARGET_CPU_VARIANT: generic
    BINSUFFIX: 64
    B2G_DEBUG: 1
  stage: build
  script:
    - ./build-b2g.sh
    - ./build-b2g.sh package
  only:
    - merge_requests
    - pipelines
  except:
    variables:
      - $GIT_CLONE_PATH =~ /koost$/

build:arm:
  before_script:
    - '[ "$(cat ${HOME}/.mozbuild/ver)" = "4" ] || curl https://packages.preprod.kaiostech.com/ndk/v4/mozbuild.tar.bz2 | tar -C ${HOME}/ -xj'
    - *global_setup
    - *koost_setup
  variables:
    DEFAULT_DOCKER_IMAGE: "${CI_REGISTRY}/re/kaios-build/next/daily:latest"
    GONK_PATH: "${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/gecko/gonk-q"
    GECKO_OBJDIR: "${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/gecko/objdir-arm-gecko"
    GONK_PRODUCT_NAME: msm8937_32go
    GET_FRAMEBUFFER_FORMAT_FROM_HWC: 1
    PLATFORM_VERSION: 29
    TARGET_ARCH: arm
    TARGET_ARCH_VARIANT: armv8-a
    TARGET_CPU_VARIANT: cortex-a53
    ANDROID_NDK: '~/.mozbuild/android-ndk-r20b-canary'
    PRODUCT_MANUFACTURER: QUALCOMM
  stage: build
  script:
    - ./build-b2g.sh
    - ./build-b2g.sh package
  only:
    - merge_requests
    - pipelines
  artifacts:
    expire_in: 2 week
    paths:
      - "objdir-arm-gecko/dist/b2g-*"
      - "push-b2g.sh"
