# (c) 2017 KAI OS TECHNOLOGIES (HONG KONG) LIMITED All rights reserved. This
# file or any portion thereof may not be reproduced or used in any manner
# whatsoever without the express written permission of KAI OS TECHNOLOGIES
# (HONG KONG) LIMITED. KaiOS is the trademark of KAI OS TECHNOLOGIES (HONG KONG)
# LIMITED or its affiliate company and may be registered in some jurisdictions.
# All other trademarks are the property of their respective owners.

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
    - if: '$CI_MERGE_REQUEST_PROJECT_PATH == "KaiOS/gecko-dev"'
    - when: never

include: '.gitlab/ci/bases.yml'

variables:
  GIT_DEPTH: 1
  # GIT_CLONE_PATH would be overidden with "koost" if pipeline gets triggered from within koost
  # also, in order for sccache, perisitent path is preferred
  GIT_CLONE_PATH: ${CI_BUILDS_DIR}/kaios/gecko

lint:
  extends: .lint_base
  stage: .pre
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline" || $CI_MERGE_REQUEST_TITLE =~ /skip-lint|^WIP\:/'
      when: never
    - when: on_success

build:arm:
  extends: .build_arm
  stage: build
  artifacts:
    expire_in: 2 week
    paths:
      - "objdir-arm-gecko/dist/b2g-*"
      - "push-b2g.sh"

build:desktop:
  extends: .build_desktop
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: never
    - when: delayed
      start_in: 10 seconds
  artifacts:
    expire_in: 1 week
    paths:
      - "objdir-desktop-gecko/dist/b2g-*"

build:emulator:
  extends: .build_emulator
  stage: build
  rules:
    - when: delayed
      start_in: 10 seconds
